### ISSUE TITLE
[Feature]: Implement OpenAI Clip in an application usable

### ISSUE THREAD

**Issue by Mikatech** [PoCInnovation/SpaceVector#14]
### Description

Create an application wich use OpenAI Clip :rocket: 

### Expected behaviour

The team have to :
- [x] Create an application which use OpenAI Clip
- [x] The application should be easily usable

### Environment

/

### Proposed solution

/

**Comment by LayBraid** [comment]
You can see the application on this link: https://huggingface.co/spaces/LayBraid/OpenIA-Implementation
