### ISSUE TITLE
[Feature]: Data Science, Logistic Regression, Neural Network & DecisionTree skills Skils

### ISSUE THREAD

**Issue by Mikatech** [PoCInnovation/SpaceVector#3]
### Description

The objective is to complete the various workshops on data science, logistic regression and decision trees.
Students will be able to explain the different concepts related to the workshops.

### Expected behaviour

- [x] Workshop [Data Science](https://github.com/PoCInnovation/Workshops/tree/master/ai/1.Data_Science_Pandas)
- [x] Workshop [Logistic Regression](https://github.com/PoCInnovation/Workshops/tree/master/ai/2.Regression_logistique)
- [x] Workshop [DecisionTree](https://github.com/PoCInnovation/Workshops/tree/master/ai/8.DecisionTree)
- [x] Workshop [Neural Network](https://github.com/PoCInnovation/Workshops/tree/master/ai/3.Neural_Network)

### Environment

/

### Proposed solution

/

**Comment by LayBraid** [comment]
Data science & Logistic Regression done for me

**Comment by Mikatech** [comment]
> Data science & Logistic Regression done for me

good job ! 🚀

**Comment by LayBraid** [comment]
All done for me
