### ISSUE TITLE
[Feature]: Learn about OpenAI Clip and understand its usefulness

### ISSUE THREAD

**Issue by Mikatech** [PoCInnovation/SpaceVector#8]
### Description

Students will discover OpenAI Clip :brain: 

### Expected behaviour

Team have to:

- [x] Look this [article](https://openai.com/blog/clip/) about Clip
- [x] Look this [video](https://www.youtube.com/watch?v=8o701AEoZ8I) about Clip
- [x] Write few sentences about what is Clip in the README.MD

### Environment

/

### Proposed solution

/

**Comment by LayBraid** [comment]
**Article**

CLIP est un réseau de neurones qui utilise la supervision du langage naturel pour former un modèle de vision par ordinateur qui peut être utilisé pour prédire des concepts visuels à partir de textes descriptifs. C'est donc est un système de classification visuelle basé sur le texte qui peut être appliqué à une grande variété de tâches de classification visuelle.

**Comment by LayBraid** [comment]
**Video**

Pour vectoriser une phrase, il faut récupérer une image de chaque mot clé de cette dernière.
Clip utilise des représentations sémantiques d'images. On peut utiliser roboflow pour extraire nos données à partir de notre dataset. On peut très facilement interrogé le modèle pour qu'il nous retourne un texte par rapport à une ou des images.
